# Generated by Django 2.2.3 on 2019-08-02 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=16)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_track', models.CharField(max_length=60)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pin', models.CharField(max_length=4)),
            ],
        ),
    ]
