# Generated by Django 2.2.3 on 2019-08-13 03:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField(default=datetime.datetime.now)),
                ('current_track', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(default=datetime.datetime.now)),
                ('pin', models.CharField(max_length=4)),
                ('country', models.CharField(blank=True, default='CA', max_length=2, null=True)),
                ('last_update', models.DateTimeField(default=datetime.datetime.now)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_id', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=4)),
                ('track_name', models.TextField()),
                ('track_id', models.CharField(max_length=25)),
                ('artists', models.CharField(max_length=255)),
                ('album_name', models.CharField(max_length=255)),
                ('explicit', models.BooleanField()),
                ('duration_ms', models.SmallIntegerField()),
                ('votes', models.SmallIntegerField(default=0)),
                ('add_time', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotifyQ.Owner')),
            ],
            options={
                'ordering': ('-votes', 'add_time'),
            },
        ),
    ]
