# Generated by Django 2.2.3 on 2019-08-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyQ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='duration_ms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='queue',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
