# Generated by Django 2.2.3 on 2019-08-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyQ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_track',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
