# Generated by Django 2.2.3 on 2019-08-04 05:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyQ', '0002_auto_20190802_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_track', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pin', models.CharField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('owner_id', models.OneToOneField(max_length=16, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='spotifyQ.Owner')),
                ('playlist_uri', models.TextField()),
                ('track_name', models.TextField()),
                ('track_id', models.CharField(max_length=25)),
                ('votes', models.SmallIntegerField()),
            ],
        ),
    ]
