# Generated by Django 2.2.3 on 2019-08-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyQ', '0003_auto_20190803_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='country',
            field=models.CharField(blank=True, default='CA', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='album_name',
            field=models.CharField(default='album', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queue',
            name='artists_names',
            field=models.CharField(default='artist', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queue',
            name='duration_ms',
            field=models.SmallIntegerField(default=3600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queue',
            name='explicit',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queue',
            name='is_playable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
