# Generated by Django 2.2.3 on 2019-08-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyQ', '0004_auto_20190803_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='votes',
            field=models.SmallIntegerField(default=0),
        ),
    ]
