# Generated by Django 2.2.3 on 2019-08-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyQ', '0006_auto_20190803_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ('-votes',)},
        ),
        migrations.RenameField(
            model_name='queue',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='queue',
            name='pin',
            field=models.CharField(default=3333, max_length=4),
            preserve_default=False,
        ),
    ]
