# Generated by Django 2.2.3 on 2019-08-04 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyQ', '0007_auto_20190804_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='is_playable',
        ),
    ]
