# Generated by Django 2.2.3 on 2019-08-05 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyQ', '0008_remove_queue_is_playable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='artists_names',
            new_name='artist_names',
        ),
    ]
