# Generated by Django 2.2.3 on 2019-08-05 00:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyQ', '0009_auto_20190804_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='id',
        ),
        migrations.AddField(
            model_name='queue',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
