# Generated by Django 2.2.3 on 2019-08-05 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyQ', '0010_auto_20190804_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='uuid',
            new_name='_uuid',
        ),
    ]
