# Generated by Django 2.2.3 on 2019-08-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyQ', '0011_auto_20190804_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='artist_names',
            new_name='artists',
        ),
    ]
