# Generated by Django 2.2.3 on 2019-08-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyQ', '0012_auto_20190805_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
