# Generated by Django 2.2.3 on 2019-08-07 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyQ', '0013_auto_20190807_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='owner',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
