# Generated by Django 2.2.3 on 2019-08-09 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyQ', '0014_auto_20190807_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='playlist_uri',
        ),
    ]
