# Generated by Django 2.2.3 on 2019-08-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyQ', '0015_remove_queue_playlist_uri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'managed': True, 'ordering': ('-votes',)},
        ),
        migrations.AddField(
            model_name='owner',
            name='playlist_uri',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
