# Generated by Django 2.2.3 on 2019-08-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyQ', '0016_auto_20190809_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='playlist_uri',
            field=models.CharField(max_length=255),
        ),
    ]
