# Generated by Django 2.2.3 on 2019-08-10 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyQ', '0017_auto_20190809_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 10, 0, 6, 58, 740565)),
        ),
    ]
