# Generated by Django 2.2.3 on 2019-08-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyQ', '0018_queue_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='add_time',
            field=models.DateTimeField(),
        ),
    ]
