# Generated by Django 2.2.3 on 2019-08-10 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyQ', '0019_auto_20190810_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'managed': True, 'ordering': ('-votes', 'add_time')},
        ),
        migrations.AddField(
            model_name='owner',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
